version: '3.7'
services:
  quartz-poc:
    image: quartz-poc
    build:
      context: ./quartz-poc
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    restart: always
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/:/docker-entrypoint-initdb.d/
volumes:
  pgdata:
